#' @title Wrapper function to import data.frame to phyloseq
#' @description \code{data_to_phyloseq} Import data.frame to phyloseq
#' @param dataset_name Character. 'ushio_2022_prsb', 'ushio_2023a_elife' or 'ushio_2023b_elife'.
#' @export
#' @examples
#' # data_to_phyloseq()
data_to_phyloseq <- function(dataset_name) {
  dataset_list <- c("ushio_2022_prsb", "ushio_2023a_elife", "ushio_2023b_elife")
  # Check arguments
  if (!(dataset_name %in% dataset_list)) {
    stop("Invalid dataset name!")
  }

  # Import Ushio (2022) Proceedings B
  if (dataset_name == dataset_list[1]) {
    data_loader(dataset_name)
    # Import
    ps <- phyloseq::phyloseq(phyloseq::otu_table(ushio_2022_prsb_df_asvtab_copy, taxa_are_rows = FALSE),
                             phyloseq::sample_data(ushio_2022_prsb_df_sample),
                             phyloseq::tax_table(as.matrix(ushio_2022_prsb_df_taxa)))
    # Leave comment on the phyloseq object
    comment(ps) <- dataset_list[1]
  }

  # Import Ushio et al. (2023a) eLife
  if (dataset_name == dataset_list[2]) {
    data_loader(dataset_name)
    # Import
    ps <- phyloseq::phyloseq(phyloseq::otu_table(ushio_2023a_elife_df_asvtab_copy, taxa_are_rows = FALSE),
                             phyloseq::sample_data(ushio_2023a_elife_df_sample),
                             phyloseq::tax_table(as.matrix(ushio_2023a_elife_df_taxa)))
    # Leave comment on the phyloseq object
    comment(ps) <- dataset_list[2]
  }

  # Import Ushio et al. (2023b) eLife
  if (dataset_name == dataset_list[3]) {
    data_loader(dataset_name)
    # Import
    ps <- phyloseq::phyloseq(phyloseq::otu_table(ushio_2023b_elife_df_asvtab_copy, taxa_are_rows = FALSE),
                             phyloseq::sample_data(ushio_2023b_elife_df_sample),
                             phyloseq::tax_table(as.matrix(ushio_2023b_elife_df_taxa)))
    # Leave comment on the phyloseq object
    comment(ps) <- dataset_list[3]
  }

  # Return phyloseq object
  return(ps)
}


#' @title Visualize multitaxa time series
#' @description \code{view_ts_multitax} Visualize multitaxa time series
#' @param ps_obj `phyloseq` object. Recommend using `phyloseq` object generated by `reed::data_to_phyloseq`.
#' @param phy_rank Character. Name of phylogeny rank.
#' @param top_taxa_n Numeric. The number of top taxa to be shown.
#' @param remove_others Logical. If TRUE, "Others" and "Undetermined" are not shown.
#' @export
#' @examples
#' # view_ts_multitax()
view_ts_multitax <- function(ps_obj, phy_rank, top_taxa_n = 11, remove_others = TRUE) {
  dataset_list <- c("ushio_2022_prsb", "ushio_2023a_elife", "ushio_2023b_elife")
  # Store data name
  dataname <- comment(ps_obj)
  if (!(dataname %in% dataset_list)) {
    message("This function is designed to handle a `phyloseq` object generated by reed. \nYou may use other `phyloseq` object, but the results might not be what you want.")
  }

  # Bundle taxa
  ps_obj <- macamseq::taxa_name_bundle(ps_obj, phy_rank, top_taxa_n = top_taxa_n)
  phyloseq::tax_table(ps_obj) <- phyloseq::tax_table(ps_obj)[,c("bundled_tax")]
  ps_obj <- speedyseq::tax_glom(ps_obj, taxrank = "bundled_tax")

  if (remove_others) {
    ps_obj <- phyloseq::prune_taxa(! (phyloseq::tax_table(ps_obj)[,"bundled_tax"] %in% c("Others", "Undetermined")), ps_obj)
  }

  # Generate ggplot2 object
  ps_m <- speedyseq::psmelt(ps_obj)
  g1 <- ggplot2::ggplot(ggplot2::aes(x = ps_m$date, y = ps_m$Abundance, color = ps_m$bundled_tax)) +
    ggplot2::geom_line()

  # Add plot/study site information
  if (dataname == dataset_list[1]) g1 <- g1 + ggplot2::facet_wrap(. ~ ps_m$plot)
  if (dataname == dataset_list[2]) g1 <- g1 + ggplot2::facet_wrap(. ~ ps_m$site_code)
  if (dataname == dataset_list[3]) g1 <- g1 + ggplot2::facet_wrap(. ~ ps_m$plot)

  # Return phyloseq object
  return(g1)
}



#' @title Visualize single taxon time series
#' @description \code{view_ts_singletax} Visualize single taxon time series
#' @param ps_obj `phyloseq` object. Recommend using `phyloseq` object generated by `reed::data_to_phyloseq`.
#' @param taxon Character. Taxon name.
#' @param phy_rank Character. Name of phylogeny rank.
#' @export
#' @examples
#' # view_ts_singletax()
view_ts_singletax <- function(ps_obj, taxon, phy_rank) {
  dataset_list <- c("ushio_2022_prsb", "ushio_2023a_elife", "ushio_2023b_elife")
  # Store data name
  dataname <- comment(ps_obj)
  if (!(dataname %in% dataset_list)) {
    message("This function is designed to handle a `phyloseq` object generated by reed. \nYou may use other `phyloseq` object, but the results might not be what you want.")
  }

  # Bundle taxa
  valid_tax <- phyloseq::tax_table(ps_obj)[,phy_rank] == taxon
  ps_obj <- phyloseq::prune_taxa(phyloseq::taxa_names(ps_obj)[as.logical(valid_tax)], ps_obj)
  ps_obj <- speedyseq::tax_glom(ps_obj, taxrank = phy_rank)

  # Generate ggplot2 object
  ps_m <- speedyseq::psmelt(ps_obj)
  g1 <- ggplot2::ggplot(ggplot2::aes(x = ps_m$date, y = ps_m$Abundance))

  # Add plot/study site information
  if (dataname == dataset_list[1]) g1 <- g1 + ggplot2::geom_line(ggplot2::aes(color = ps_m$plot))
  if (dataname == dataset_list[2]) g1 <- g1 + ggplot2::geom_line(ggplot2::aes(color = ps_m$site_code))
  if (dataname == dataset_list[3]) g1 <- g1 + ggplot2::geom_line(ggplot2::aes(color = ps_m$plot))

  # Return phyloseq object
  return(g1)
}
